<select id='judete' class='login-input margin20' name="judete">
    <option value="0" hidden>Alege Judet</option>
    <option value="Alba">Alba</option>
    <option value="Arad">Arad</option>
    <option value="Arges">Arges</option>
    <option value="Bacau">Bacau</option>
    <option value="Bihor">Bihor</option>
    <option value="Bistrita Nasaud">Bistrita Nasaud</option>
    <option value="Botosani">Botosani</option>
    <option value="Brasov">Brasov</option>
    <option value="Braila">Braila</option>
    <option value="Bucuresti">Bucuresti</option>
    <option value="Buzau">Buzau</option>
    <option value="Caras Severin">Caras Severin</option>
    <option value="Calarasi">Calarasi</option>
    <option value="Cluj">Cluj</option>
    <option value="Constanta">Constanta</option>
    <option value="Covasna">Covasna</option>
    <option value="Dambovita">Dambovita</option>
    <option value="Dolj">Dolj</option>
    <option value="Galati">Galati</option>
    <option value="Giurgiu">Giurgiu</option>
    <option value="Gorj">Gorj</option>
    <option value="Harghita">Harghita</option>
    <option value="Hunedoara">Hunedoara</option>
    <option value="Ialomita">Ialomita</option>
    <option value="Iasi">Iasi</option>
    <option value="Ilfov">Ilfov</option>
    <option value="Maramures">Maramures</option>
    <option value="Mehedinti">Mehedinti</option>
    <option value="Mures">Mures</option>
    <option value="Neamt">Neamt</option>
    <option value="Olt">Olt</option>
    <option value="Prahova">Prahova</option>
    <option value="Satu Mare">Satu Mare</option>
    <option value="Salaj">Salaj</option>
    <option value="Sibiu">Sibiu</option>
    <option value="Suceava">Suceava</option>
    <option value="Teleorman">Teleorman</option>
    <option value="Timis">Timis</option>
    <option value="Tulcea">Tulcea</option>
    <option value="Vaslui">Vaslui</option>
    <option value="Valcea">Valcea</option>
    <option value="Vrancea">Vrancea</option>
</select>

<select id='oras' class='login-input margin20' name="judete">
    <option value="0" hidden>Alege Oraș</option>
    <option value="Abrud">Abrud</option>
    <option value="Adjud">Adjud</option>
    <option value="Aiud">Aiud</option>
    <option value="Alba Iulia">Alba Iulia</option>
    <option value="Aleşd">Aleşd</option>
    <option value="Alexandria">Alexandria</option>
    <option value="Agnita">Agnita</option>
    <option value="Anina">Anina</option>
    <option value="Aninoasa">Aninoasa</option>
    <option value="Arad">Arad</option>
    <option value="Avrig">Avrig</option>
    <option value="Azuga">Azuga</option>
    <option value="Babadag">Babadag</option>
    <option value="Bacău">Bacău</option>
    <option value="Baia de Aramă">Baia de Aramă</option>
    <option value="Baia de Arieş">Baia de Arieş</option>
    <option value="Baia Mare">Baia Mare</option>
    <option value="Baia Sprie">Baia Sprie</option>
    <option value="Balş">Balş</option>
    <option value="Baraolt">Baraolt</option>
    <option value="Băicoi">Băicoi</option>
    <option value="Băile Govora">Băile Govora</option>
    <option value="Băile Herculane">Băile Herculane</option>
    <option value="Băile Olăneşti">Băile Olăneşti</option>
    <option value="Băileşti">Băileşti</option>
    <option value="Băile Tuşnad">Băile Tuşnad</option>
    <option value="Bălan">Bălan</option>
    <option value="Bârlad">Bârlad</option>
    <option value="Bocşa">Bocşa</option>
    <option value="Borsec">Borsec</option>
    <option value="Beclean">Beclean</option>
    <option value="Beiuş">Beiuş</option>
    <option value="Bereşti">Bereşti</option>
    <option value="Bicaz">Bicaz</option>
    <option value="Bistriţa">Bistriţa</option>
    <option value="Blaj">Blaj</option>
    <option value="Boldeşti-Scăieni">Boldeşti-Scăieni</option>
    <option value="Bolintin-Vale">Bolintin-Vale</option>
    <option value="Borşa">Borşa</option>
    <option value="Botoşani">Botoşani</option>
    <option value="Brad">Brad</option>
    <option value="Braşov">Braşov</option>
    <option value="Brăila">Brăila</option>
    <option value="Breaza">Breaza</option>
    <option value="Brezoi">Brezoi</option>
    <option value="Bucureşti">Bucureşti</option>
    <option value="Budeşti">Budeşti</option>
    <option value="Buftea">Buftea</option>
    <option value="Buhuşi">Buhuşi</option>
    <option value="Bumbeşti-Jiu">Bumbeşti-Jiu</option>
    <option value="Buşteni">Buşteni</option>
    <option value="Buziaş">Buziaş</option>
    <option value="Buzău">Buzău</option>
    <option value="Calafat">Calafat</option>
    <option value="Carei">Carei</option>
    <option value="Caracal">Caracal</option>
    <option value="Caransebeş">Caransebeş</option>
    <option value="Cavnic">Cavnic</option>
    <option value="Călan">Călan</option>
    <option value="Călăraşi">Călăraşi</option>
    <option value="Călimăneşti-Căciulata">Călimăneşti-Căciulata</option>
    <option value="Câmpeni">Câmpeni</option>
    <option value="Câmpia Turzii">Câmpia Turzii</option>
    <option value="Câmpina">Câmpina</option>
    <option value="Câmpulung">Câmpulung</option>
    <option value="Câmpulung Moldovenesc">Câmpulung Moldovenesc</option>
    <option value="Cehu Silvaniei">Cehu Silvaniei</option>
    <option value="Cernavodă">Cernavodă</option>
    <option value="Chişineu-Criş">Chişineu-Criş</option>
    <option value="Cisnădie">Cisnădie</option>
    <option value="Cluj-Napoca">Cluj-Napoca</option>
    <option value="Codlea">Codlea</option>
    <option value="Comarnic">Comarnic</option>
    <option value="Comăneşti">Comăneşti</option>
    <option value="Constanţa">Constanţa</option>
    <option value="Copşa Mică">Copşa Mică</option>
    <option value="Corabia">Corabia</option>
    <option value="Costeşti">Costeşti</option>
    <option value="Covasna">Covasna</option>
    <option value="Craiova">Craiova</option>
    <option value="Cristuru Secuiesc">Cristuru Secuiesc</option>
    <option value="Cugir">Cugir</option>
    <option value="Curtici">Curtici</option>
    <option value="Curtea de Argeş">Curtea de Argeş</option>
    <option value="Darabani">Darabani</option>
    <option value="Dărmăneşti">Dărmăneşti</option>
    <option value="Dealu">Dealu</option>
    <option value="Dej">Dej</option>
    <option value="Deta">Deta</option>
    <option value="Deva">Deva</option>
    <option value="Dorohoi">Dorohoi</option>
    <option value="Drăgăneşti-Olt">Drăgăneşti-Olt</option>
    <option value="Drăgăşani">Drăgăşani</option>
    <option value="Drobeta-Turnu Severin">Drobeta-Turnu Severin</option>
    <option value="Dumbrăveni">Dumbrăveni</option>
    <option value="Eforie">Eforie</option>
    <option value="Făgăraş">Făgăraş</option>
    <option value="Făget">Făget</option>
    <option value="Fălticeni">Fălticeni</option>
    <option value="Făurei">Făurei</option>
    <option value="Feteşti">Feteşti</option>
    <option value="Fieni">Fieni</option>
    <option value="Filiaşi">Filiaşi</option>
    <option value="Focşani">Focşani</option>
    <option value="Fundulea">Fundulea</option>
    <option value="Galaţi">Galaţi</option>
    <option value="Găeşti">Găeşti</option>
    <option value="Geoagiu">Geoagiu</option>
    <option value="Gheorgheni">Gheorgheni</option>
    <option value="Gherla">Gherla</option>
    <option value="Giurgiu">Giurgiu</option>
    <option value="Gura Humorului">Gura Humorului</option>
    <option value="Haţeg">Haţeg</option>
    <option value="Hârlău">Hârlău</option>
    <option value="Hârşova">Hârşova</option>
    <option value="Horezu">Horezu</option>
    <option value="Huedin">Huedin</option>
    <option value="Hunedoara">Hunedoara</option>
    <option value="Huşi">Huşi</option>
    <option value="Ianca">Ianca</option>
    <option value="Iaşi">Iaşi</option>
    <option value="Iernut">Iernut</option>
    <option value="Ineu">Ineu</option>
    <option value="Isaccea">Isaccea</option>
    <option value="Însurăţei">Însurăţei</option>
    <option value="Întorsura Buzăului">Întorsura Buzăului</option>
    <option value="Jibou">Jibou</option>
    <option value="Jimbolia">Jimbolia</option>
    <option value="Lehliu Gară">Lehliu Gară</option>
    <option value="Lipova">Lipova</option>
    <option value="Luduş">Luduş</option>
    <option value="Lugoj">Lugoj</option>
    <option value="Lupeni">Lupeni</option>
    <option value="Mangalia">Mangalia</option>
    <option value="Marghita">Marghita</option>
    <option value="Măcin">Măcin</option>
    <option value="Mărăşeşti">Mărăşeşti</option>
    <option value="Medgidia">Medgidia</option>
    <option value="Mediaş">Mediaş</option>
    <option value="Miercurea Ciuc">Miercurea Ciuc</option>
    <option value="Mihăileşti">Mihăileşti</option>
    <option value="Mioveni">Mioveni</option>
    <option value="Mizil">Mizil</option>
    <option value="Moineşti">Moineşti</option>
    <option value="Moldova Nouă">Moldova Nouă</option>
    <option value="Moreni">Moreni</option>
    <option value="Motru">Motru</option>
    <option value="Murfatlar">Murfatlar</option>
    <option value="Nădlac">Nădlac</option>
    <option value="Năsăud">Năsăud</option>
    <option value="Năvodari">Năvodari</option>
    <option value="Negreşti">Negreşti</option>
    <option value="Negreşti-Oaş">Negreşti-Oaş</option>
    <option value="Negru Vodă">Negru Vodă</option>
    <option value="Nehoiu">Nehoiu</option>
    <option value="Novaci">Novaci</option>
    <option value="Nucet">Nucet</option>
    <option value="Ocna Mureş">Ocna Mureş</option>
    <option value="Ocna Sibiului">Ocna Sibiului</option>
    <option value="Ocnele Mari">Ocnele Mari</option>
    <option value="Odobeşti">Odobeşti</option>
    <option value="Odorheiu Secuiesc">Odorheiu Secuiesc</option>
    <option value="Olteniţa">Olteniţa</option>
    <option value="Oneşti">Oneşti</option>
    <option value="Oradea">Oradea</option>
    <option value="Oraviţa">Oraviţa</option>
    <option value="Orăştie">Orăştie</option>
    <option value="Orşova">Orşova</option>
    <option value="Otopeni">Otopeni</option>
    <option value="Oţelu Roşu">Oţelu Roşu</option>
    <option value="Ovidiu">Ovidiu</option>
    <option value="Panciu">Panciu</option>
    <option value="Paşcani">Paşcani</option>
    <option value="Pâncota">Pâncota</option>
    <option value="Petrila">Petrila</option>
    <option value="Petroşani">Petroşani</option>
    <option value="Piatra Neamţ">Piatra Neamţ</option>
    <option value="Piatra Olt">Piatra Olt</option>
    <option value="Piteşti">Piteşti</option>
    <option value="Ploieşti">Ploieşti</option>
    <option value="Plopeni">Plopeni</option>
    <option value="Pogoanele">Pogoanele</option>
    <option value="Predeal">Predeal</option>
    <option value="Pucioasa">Pucioasa</option>
    <option value="Rădăuţi">Rădăuţi</option>
    <option value="Râmnicu Sărat">Râmnicu Sărat</option>
    <option value="Râmnicu Vâlcea">Râmnicu Vâlcea</option>
    <option value="Râşnov">Râşnov</option>
    <option value="Reghin">Reghin</option>
    <option value="Reşiţa">Reşiţa</option>
    <option value="Roman">Roman</option>
    <option value="Roşiori de Vede">Roşiori de Vede</option>
    <option value="Rovinari">Rovinari</option>
    <option value="Rupea">Rupea</option>
    <option value="Salonta">Salonta</option>
    <option value="Satu Mare">Satu Mare</option>
    <option value="Săcele">Săcele</option>
    <option value="Săveni">Săveni</option>
    <option value="Sângeorz-Băi">Sângeorz-Băi</option>
    <option value="Sânnicolau Mare">Sânnicolau Mare</option>
    <option value="Scorniceşti">Scorniceşti</option>
    <option value="Sebeş">Sebeş</option>
    <option value="Sebiş">Sebiş</option>
    <option value="Seini">Seini</option>
    <option value="Segarcea">Segarcea</option>
    <option value="Sfântu Gheorghe">Sfântu Gheorghe</option>
    <option value="Sibiu">Sibiu</option>
    <option value="Sighetu Marmaţiei">Sighetu Marmaţiei</option>
    <option value="Sighişoara">Sighişoara</option>
    <option value="Simeria">Simeria</option>
    <option value="Sinaia">Sinaia</option>
    <option value="Siret">Siret</option>
    <option value="Slatina">Slatina</option>
    <option value="Slănic">Slănic</option>
    <option value="Slănic Moldova">Slănic Moldova</option>
    <option value="Slobozia">Slobozia</option>
    <option value="Solca">Solca</option>
    <option value="Sovata">Sovata</option>
    <option value="Strehaia">Strehaia</option>
    <option value="Suceava">Suceava</option>
    <option value="Sulina">Sulina</option>
    <option value="Şimleu Silvaniei">Şimleu Silvaniei</option>
    <option value="Ştei">Ştei</option>
    <option value="Tălmaciu">Tălmaciu</option>
    <option value="Tăşnad">Tăşnad</option>
    <option value="Târgovişte">Târgovişte</option>
    <option value="Târgu Bujor">Târgu Bujor</option>
    <option value="Târgu Cărbuneşti">Târgu Cărbuneşti</option>
    <option value="Târgu Frumos">Târgu Frumos</option>
    <option value="Târgu Jiu">Târgu Jiu</option>
    <option value="Târgu Lăpuş">Târgu Lăpuş</option>
    <option value="Târgu Mureş">Târgu Mureş</option>
    <option value="Târgu Neamţ">Târgu Neamţ</option>
    <option value="Târgu Ocna">Târgu Ocna</option>
    <option value="Târgu Secuiesc">Târgu Secuiesc</option>
    <option value="Târnăveni">Târnăveni</option>
    <option value="Techirghiol">Techirghiol</option>
    <option value="Tecuci">Tecuci</option>
    <option value="Teiuş">Teiuş</option>
    <option value="Timişoara">Timişoara</option>
    <option value="Tismana">Tismana</option>
    <option value="Titu">Titu</option>
    <option value="Topliţa">Topliţa</option>
    <option value="Topoloveni">Topoloveni</option>
    <option value="Tulcea">Tulcea</option>
    <option value="Turda">Turda</option>
    <option value="Turnu Măgurele">Turnu Măgurele</option>
    <option value="Ţăndărei">Ţăndărei</option>
    <option value="Ţicleni">Ţicleni</option>
    <option value="Uricani">Uricani</option>
    <option value="Urlaţi">Urlaţi</option>
    <option value="Urziceni">Urziceni</option>
    <option value="Valea lui Mihai">Valea lui Mihai</option>
    <option value="Vaslui">Vaslui</option>
    <option value="Vaşcău">Vaşcău</option>
    <option value="Vatra Dornei">Vatra Dornei</option>
    <option value="Vălenii de Munte">Vălenii de Munte</option>
    <option value="Vânju Mare">Vânju Mare</option>
    <option value="Victoria">Victoria</option>
    <option value="Videle">Videle</option>
    <option value="Vişeu de Sus">Vişeu de Sus</option>
    <option value="Vlăhiţa">Vlăhiţa</option>
    <option value="Vulcan">Vulcan</option>
    <option value="Zalău">Zalău</option>
    <option value="Zărneşti">Zărneşti</option>
    <option value="Zimnicea">Zimnicea</option>
    <option value="Zlatna">Zlatna</option>
</select>