<select id='tari' class='login-input' name="addressCountry">
    <option hidden>Țară*</option>
    <option value="RO">România</option>
    <option value="GB">Regatul Unitate</option>
    <option value="AL">Albania</option>
    <option value="AD">Andorra</option>
    <option value="AT">Austria</option>
    <option value="BY">Bielorusia</option>
    <option value="BE">Belgia</option>
    <option value="BA">Bosnia si Hertegovina</option>
    <option value="BG">Bulgaria</option>
    <option value="HR">Croaţia</option>
    <option value="CY">Cipru</option>
    <option value="CZ">Republica Cehă</option>
    <option value="FR">Franţa</option>
    <option value="GI">Gibraltar</option>
    <option value="DE">Germania</option>
    <option value="GR">Grecia</option>
    <option value="VA">Vatican</option>
    <option value="HU">Ungaria</option>
    <option value="IT">Italia</option>
    <option value="LI">Liechtenstein</option>
    <option value="LU">Luxemburg</option>
    <option value="MK">Macedonia</option>
    <option value="MT">Malta</option>
    <option value="MD">Moldova</option>
    <option value="MC">Monaco</option>
    <option value="ME">Muntenegru</option>
    <option value="NL">Olanda</option>
    <option value="PL">Polonia</option>
    <option value="PT">Portugalia</option>
    <option value="SM">San Marino</option>
    <option value="RS">Serbia</option>
    <option value="SK">Slovacia</option>
    <option value="SI">Slovenia</option>
    <option value="ES">Spania</option>
    <option value="UA">Ucraina</option>
    <option value="DK">Danemarca</option>
    <option value="EE">Estonia</option>
    <option value="FO">Insulele Feroe</option>
    <option value="FI">Finlanda</option>
    <option value="GL">Groenlanda</option>
    <option value="IS">Islanda</option>
    <option value="IE">Irlanda</option>
    <option value="LV">Letonia</option>
    <option value="LT">Lituania</option>
    <option value="NO">Norvegia</option>
    <option value="SJ">Insulele Svalbard și Jan Mayen</option>
    <option value="SE">Suedia</option>
    <option value="CH">Elveţia</option>
    <option value="TR">Curcan</option>
</select>