<?php require_once "design/dependecies.php"; ?>
<title>Investy - Investiție</title>
<body>
<?php require_once "design/nav.php"; ?>
<section class="investitie column header-element padding-all not-fullscreen">
    <a href="#" class="box-video margin80">
        <img src="./static/content/investitie.webp" alt="video-comunitate"/>
        <img src="./static/content/icons/play.svg" alt="play-button">
    </a>
    <div class="box-investitie width100 margin40 row-left">
        <div class="box-subtitle margin20 mr55 row-left show">
            <div class="line"></div>
            <h2 class="sub-title">Restaurant Alexo</h2>
        </div>
        <div class="box-subtitle margin20 row-left show">
            <div class="line"></div>
            <h2 class="sub-title">Valoarea investiției: <span class="blue-color"> 60.000€</span></h2>
        </div>
    </div>
    <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat erat at velit interdum laoreet. Donec ultrices nec nibh id pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec mollis quam dolor. Ut vel ipsum vitae arcu placerat malesuada. Donec ac leo egestas nisi dignissim eleifend. Cras tincidunt consequat felis, sit amet eleifend lorem aliquet sed. <br/><br/> Nunc nec odio sed purus tincidunt varius. Sed vel nibh at felis tincidunt rutrum vitae at leo. Mauris ac egestas turpis. Maecenas accumsan arcu in felis consectetur pulvinar. Curabitur nec sodales lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam id odio sagittis dui posuere aliquam. Nunc sit amet lacus mattis, feugiat elit et, aliquam nunc. Praesent rhoncus enim est, non aliquam nibh iaculis vestibulum. Vestibulum at ligula sed purus tristique consectetur eu nec erat. Proin lobortis neque et leo bibendum tristique. <br/><br/> Nulla condimentum porttitor euismod. Pellentesque pharetra ultrices libero quis volutpat. Curabitur et magna mollis, dapibus nibh non, tempor odio. Nunc a cursus felis. Etiam id tellus leo. Nunc eget semper eros. Aenean rhoncus, mi id ultricies vehicula, neque mi euismod odio, vitae ullamcorper ex tellus ac massa. Duis quis enim placerat, placerat justo non, dictum eros. Vivamus pretium dui quis elit tincidunt ultrices. Duis eros nisl, laoreet accumsan ante vel, lacinia egestas neque. <br/><br/></p>
    <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat erat at velit interdum laoreet. Donec ultrices nec nibh id pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec mollis quam dolor. Ut vel ipsum vitae arcu placerat malesuada. Donec ac leo egestas nisi dignissim eleifend. Cras tincidunt consequat felis, sit amet eleifend lorem aliquet sed. <br/><br/> Nunc nec odio sed purus tincidunt varius. Sed vel nibh at felis tincidunt rutrum vitae at leo. Mauris ac egestas turpis. Maecenas accumsan arcu in felis consectetur pulvinar. Curabitur nec sodales lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam id odio sagittis dui posuere aliquam. Nunc sit amet lacus mattis, feugiat elit et, aliquam nunc. Praesent rhoncus enim est, non aliquam nibh iaculis vestibulum. Vestibulum at ligula sed purus tristique consectetur eu nec erat. Proin lobortis neque et leo bibendum tristique. <br/><br/> Nulla condimentum porttitor euismod. Pellentesque pharetra ultrices libero quis volutpat. Curabitur et magna mollis, dapibus nibh non, tempor odio. Nunc a cursus felis. Etiam id tellus leo. Nunc eget semper eros. Aenean rhoncus, mi id ultricies vehicula, neque mi euismod odio, vitae ullamcorper ex tellus ac massa. Duis quis enim placerat, placerat justo non, dictum eros. Vivamus pretium dui quis elit tincidunt ultrices. Duis eros nisl, laoreet accumsan ante vel, lacinia egestas neque. <br/><br/></p>
    <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat erat at velit interdum laoreet. Donec ultrices nec nibh id pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec mollis quam dolor. Ut vel ipsum vitae arcu placerat malesuada. Donec ac leo egestas nisi dignissim eleifend. Cras tincidunt consequat felis, sit amet eleifend lorem aliquet sed. <br/><br/> Nunc nec odio sed purus tincidunt varius. Sed vel nibh at felis tincidunt rutrum vitae at leo. Mauris ac egestas turpis. Maecenas accumsan arcu in felis consectetur pulvinar. Curabitur nec sodales lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam id odio sagittis dui posuere aliquam. Nunc sit amet lacus mattis, feugiat elit et, aliquam nunc. Praesent rhoncus enim est, non aliquam nibh iaculis vestibulum. Vestibulum at ligula sed purus tristique consectetur eu nec erat. Proin lobortis neque et leo bibendum tristique. <br/><br/> Nulla condimentum porttitor euismod. Pellentesque pharetra ultrices libero quis volutpat. Curabitur et magna mollis, dapibus nibh non, tempor odio. Nunc a cursus felis. Etiam id tellus leo. Nunc eget semper eros. Aenean rhoncus, mi id ultricies vehicula, neque mi euismod odio, vitae ullamcorper ex tellus ac massa. Duis quis enim placerat, placerat justo non, dictum eros. Vivamus pretium dui quis elit tincidunt ultrices. Duis eros nisl, laoreet accumsan ante vel, lacinia egestas neque. <br/><br/></p>

</section>
<?php require_once "design/footer.php"; ?>
</body>
</html>
